Plan window improvement
spc-group/haven pull request #311
Opened 2024-11-21 18:37 UTC by Cathyhjj

Things to do before merging:

- [ ] add tests
- [ ] write docs
- [ ] update iconfig_testing.toml
- [ ] flake8, black, and isort

2024-12-15 20:40 UTC, Cathyhjj commented
do not review this PR yet, I wanted to add #329 in this PR too

2025-01-07 20:24 UTC, canismarko commented
This numpy error is fixed in another PR: https://github.com/spc-group/haven/pull/339/commits/a8235951e3270553d05ed422785e853219fd59e7

The rest of the tests pass so I'll just review it as is.

2025-01-07 20:51 UTC, canismarko requested changes

2025-01-07 20:51 UTC, canismarko commented on src/firefly/plans/grid_scan.py
> +    def change_background(self, state):
Can this method be moved to the RegionsDisplay class so we don't need to write it twice? It looks identical between the line scan and grid scan versions.

2025-01-07 20:51 UTC, canismarko commented on src/firefly/plans/line_scan.py
> +    update_step_signal = Signal(int)
What is this signal for? It looks like `LineScanDisplay.update_regions_step_size()` emits this signal, but all it does is connect directly to `LineScanRegion.update_step_size()`. Could `LineScanDisplay.update_regions_step_size()` call directly `LineScanRegion.update_step_size()`?

If we really need a signal, can it be renamed to describe what actually happened? Signals typically represent some changed state in the application (e.g. "checked", "textChanged" etc) instead of an action to take (that's a slot).

2025-01-07 20:51 UTC, canismarko commented on src/firefly/plans/line_scan.py
> +    def update_regions_step_size(self, value):
`"value"` is a bit vague. How about *step_size* or something like that?

2025-01-07 20:51 UTC, canismarko commented on src/firefly/tests/test_grid_scan_window.py
> +    region_1.scan_pts_spin_box.setValue(1)
Good call testing for these edge cases!

2025-01-07 22:00 UTC, Cathyhjj commented on src/firefly/plans/grid_scan.py
> +    def change_background(self, state):
Good idea!

2025-01-07 22:24 UTC, Cathyhjj commented on src/firefly/plans/line_scan.py
> +    update_step_signal = Signal(int)
Good idea, fixed, see the changed codes

2025-01-07 22:24 UTC, Cathyhjj commented on src/firefly/plans/line_scan.py
> +    def update_regions_step_size(self, value):
changed

2025-01-07 22:49 UTC, canismarko approved these changes
Looks good, feel free to merge when ready.

2025-01-07 22:59 UTC, merged